version: '3'

services: 
    site.debug:
        build:
            context: .
            dockerfile: '${PWD}/@mrsauravsahu/site/debug.dockerfile'
        environment: 
            - BLOGS_BASE_URL=http://api.debug:5000
        ports: 
            - '3000:3000'

    api.debug:
        build:
            context: .
            dockerfile: ${PWD}/blogs/debug.dockerfile
        ports: 
            - '5000:5000'
        volumes: 
            - './blogs:/app'
            - './store:/store'
        