version: '3'

services: 
    api:
        build:
            context: ./blogs
            dockerfile: ${PWD}/blogs/dockerfile
        ports: 
            - '5000:80'
        volumes: 
            - './store:/store'
        environment: 
            - Blogs__AppName=${Blogs__AppName}
            - Blogs__Version=${Blogs__Version}
            - Blogs__ContactEmail=${Blogs__ContactEmail}
            - Blogs__StoreBasePath=/store
            - Files__BasePath=/store
            - Github__Token=${Github__Token}
        