version: '3'

services: 
    api:
        build:
            context: ./blogs
            dockerfile: ${PWD}/blogs/dockerfile
        ports: 
            - '8080:80'
        volumes: 
            - './store:/store'
        environment: 
            - blogs:AppName=@mrsauravsahu/blogs
            - blogs:ContactEmail=mrsauravsahu@outlook.com
            - blogs:Version=0.0.0
            - blogs:StoreBasePath=/store
            - blogs:files:BasePath=/store
        