FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

WORKDIR /app/blogs.api

COPY . .

RUN dotnet restore

RUN dotnet publish -c Release -o out -r linux-musl-x64

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

WORKDIR /app

COPY --from=build /app/blogs.api/out .

CMD ./blogs.api

EXPOSE 80