version: '3'

services: 
    api:
        build:
            context: .
            dockerfile: blogs.api.dev.dockerfile
        ports: 
            - '5000:5000'
        volumes: 
            - '.:/app'
