name: Workflow for blogs project

env:
  NODE_VERSION: "12.8.0"
  NODE_ENV: test
  PROJECT: "@mrsauravsahu/blogs"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-16.04
    if: startsWith(github.head_ref, 'blogs') == true

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
        dotnet-version: '3.1.x'

      - name: build app locally
        run: |
          docker build api  

      - name: copy test .env file to build
        working-directory: ${{ env.PROJECT }}
        run: cp .env.test build/.env

      - name: run tests
        working-directory: ${{ env.PROJECT }}
        run: pnpm t
