name: Workflow for blogs project

env:
  NODE_VERSION: "12.8.0"
  NODE_ENV: test
  PROJECT: "@mrsauravsahu/blogs"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-16.04
    if: startsWith(github.head_ref, 'blogs') == true

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: build app locally
        run: |
          docker build -f ./blogs/dockerfile ./blogs
