name: Workflow for blogs project

env:
  NODE_VERSION: "12.8.0"
  NODE_ENV: test
  PROJECT: "@mrsauravsahu/blogs"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-16.04
    # if: startsWith(github.ref, 'refs/heads/blogs') == true

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: check ref
        run: echo ${{ github.head_ref }} ${{ github.ref }}

      - name: install pnpm
        uses: pnpm/action-setup/@v1.2.0
        with:
          version: 4.11.1
          run_install: |
            - recursive: true

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build project
        working-directory: ${{ env.PROJECT }}
        run: pnpm run build

      - name: copy test .env file to build
        working-directory: ${{ env.PROJECT }}
        run: cp .env.test build/.env

      - name: run integration tests
        working-directory: ${{ env.PROJECT }}
        run: pnpm run e2e
