name: Workflow for blogs project

env:
  NODE_VERSION: "12.8.0"
  NODE_ENV: test
  PROJECT: "@mrsauravsahu/blogs"

on:
  push:
    branches:
      - main/blogs
  pull_request:
    branches:
      - main/blogs

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: install pnpm
        uses: pnpm/action-setup/@v1.2.0
        with:
          version: 4.11.1
          run_install: |
            - recursive: true

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: run tests
        working-directory: ${{ env.PROJECT }}
        run: npm t
