name: CD
on: 
  push:
    branches: 
      - 'main/**'

jobs:
  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-18.04

    steps:
    - name: checkout to branch
      uses: actions/checkout@v1
    
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install dependencies
      run: yarn

    - name: run tests
      run: yarn build

  deploy:
    name: Deploy to GitHub pages
    needs: build
    runs-on: ubuntu-18.04

    steps:
    - name: checkout to branch
      uses: actions/checkout@v1
    
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install dependencies
      run: yarn

    - name: deploy site to GitHub pages
      run: yarn deploy

