name: CD
on: push 
#  push:
#    branches: 
#      - 'main/**'

jobs:
  buld_and_deploy:
    name: Build and Deploy to GitHub pages
    runs-on: ubuntu-18.04

    steps:
    - name: checkout to branch
      uses: actions/checkout@v1
    
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install dependencies
      run: yarn

    - name: build project
      run: yarn build

    - name: deploy site to GitHub pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_GH_PAGES_SECRET }}
        BASE_BRANCH: main/develop
        BRANCH: gh-pages
        FOLDER: public
