name: ci-cd for mrsauravsahu.github.io

env:
  NODE_VERSION: "12.8.0"
  NODE_ENV: development
  COMPONENTS_WORKING_DIRECTORY: projects/components
  SITE_WORKING_DIRECTORY: projects/site
  SITE_EXPORT_DIRECTORY: projects/site/__sapper__/export
  DEPLOY_BRANCH_REF: refs/heads/develop
  GITHUB_PAGES_PUBLISH_BRANCH: master

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: install pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 4.11.1
          run_install: |
            - recursive: true

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build web components
        working-directory: ${{ env.COMPONENTS_WORKING_DIRECTORY }}
        run: npm run build

      - name: build portfolio
        working-directory: ${{ env.SITE_WORKING_DIRECTORY }}
        run: npm run export

      - name: run portfolio tests
        working-directory: ${{ env.SITE_WORKING_DIRECTORY }}
        run: npm t

      - name: deploy portfolio to github pages
        if: ${{ github.ref == env.DEPLOY_BRANCH_REF }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.SITE_EXPORT_DIRECTORY }}
          publish_branch: ${{ env.GITHUB_PAGES_PUBLISH_BRANCH }}
