name: CI
on: push

jobs:
  lint_test_build:
    name: Lint, Test and Build the project
    runs-on: ubuntu-18.04

    steps:
    - name: checkout to branch
      uses: actions/checkout@v1
    
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install dependencies
      run: yarn

    - name: run linter task
      run: yarn lint

    - name: run tests
      run: yarn test

    - name: build project
      run: yarn build
