name: ci

env:
  NODE_VERSION: '12.8.0'

on:
  push: 
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: setup node.js 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install dependencies
        working-directory: site
        run: npm i

      - name: run tests
        working-directory: site
        run: npm t

      - name: build 
        working-directory: site
        run: npm run export
