name: Deploy site to Github pages

on:
  push:
    branches:
      - develop

env:
  NODE_VERSION: "12.8.0"
  BLOGS_BASE_URL: http://localhost:5000
  COMPONENTS_WORKING_DIRECTORY: "@mrsauravsahu/components"
  SITE_WORKING_DIRECTORY: "@mrsauravsahu/site"
  SITE_EXPORT_DIRECTORY: "@mrsauravsahu/site/__sapper__/export"
  GITHUB_PAGES_PUBLISH_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: install pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 4.11.1
          run_install: |
            - recursive: true

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build web components
        working-directory: ${{ env.COMPONENTS_WORKING_DIRECTORY }}
        run: pnpm build:components

      - name: export site
        run: pnpm site:export
