name: CI for develop - project checks

env:
  NODE_VERSION: "12.8.0"
  NODE_ENV: development
  COMPONENTS_PROJECT: "@mrsauravsahu/components"
  SITE_PROJECT: "@mrsauravsahu/site"
  SITE_EXPORT_DIRECTORY: "@mrsauravsahu/site/__sapper__/export"
  BLOGS_PROJECT: "@mrsauravsahu/blogs"
  GITHUB_PAGES_PUBLISH_BRANCH: master

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: install pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 4.11.1
          run_install: |
            - recursive: true

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # checks for site
      - name: build web components
        working-directory: ${{ env.COMPONENTS_PROJECT }}
        run: npm run build

      - name: run portfolio tests
        working-directory: ${{ env.SITE_PROJECT }}
        run: npm t

      # checks for blogs project
      - name: build project
        working-directory: ${{ env.BLOGS_PROJECT }}
        run: pnpm run build

      - name: copy test .env file to build
        working-directory: ${{ env.BLOGS_PROJECT }}
        run: cp .env.test build/.env

      - name: run integration tests
        working-directory: ${{ env.BLOGS_PROJECT }}
        run: pnpm run e2e
